/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoResumeRouteImport } from './routes/video-resume'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CodingRouteImport } from './routes/coding'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterIndexRouteImport } from './routes/recruiter.index'
import { Route as RecruiterTeamRouteImport } from './routes/recruiter.team'
import { Route as RecruiterShortlistedRouteImport } from './routes/recruiter.shortlisted'
import { Route as RecruiterSettingsRouteImport } from './routes/recruiter.settings'
import { Route as RecruiterResumeIntelligenceRouteImport } from './routes/recruiter.resume-intelligence'
import { Route as RecruiterReportsRouteImport } from './routes/recruiter.reports'
import { Route as RecruiterRecommendationsRouteImport } from './routes/recruiter.recommendations'
import { Route as RecruiterPipelineRouteImport } from './routes/recruiter.pipeline'
import { Route as RecruiterPerformanceRouteImport } from './routes/recruiter.performance'
import { Route as RecruiterNotificationsRouteImport } from './routes/recruiter.notifications'
import { Route as RecruiterMessagesRouteImport } from './routes/recruiter.messages'
import { Route as RecruiterJobsRouteImport } from './routes/recruiter.jobs'
import { Route as RecruiterInterviewsRouteImport } from './routes/recruiter.interviews'
import { Route as RecruiterInterviewInvitesRouteImport } from './routes/recruiter.interview-invites'
import { Route as RecruiterInsightsRouteImport } from './routes/recruiter.insights'
import { Route as RecruiterDashboardRouteImport } from './routes/recruiter.dashboard'
import { Route as RecruiterCompanyRouteImport } from './routes/recruiter.company'
import { Route as RecruiterCandidatesRouteImport } from './routes/recruiter.candidates'
import { Route as RecruiterApplicationsRouteImport } from './routes/recruiter.applications'
import { Route as RecruiterAnalyticsRouteImport } from './routes/recruiter.analytics'
import { Route as RecruiterAiAnalysisRouteImport } from './routes/recruiter.ai-analysis'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as RecruiterJobsCreateRouteImport } from './routes/recruiter.jobs.create'
import { Route as RecruiterInterviewMonitorInterviewIdRouteImport } from './routes/recruiter.interview-monitor.$interviewId'

const VideoResumeRoute = VideoResumeRouteImport.update({
  id: '/video-resume',
  path: '/video-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingRoute = CodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterIndexRoute = RecruiterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterTeamRoute = RecruiterTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterShortlistedRoute = RecruiterShortlistedRouteImport.update({
  id: '/shortlisted',
  path: '/shortlisted',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterSettingsRoute = RecruiterSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterResumeIntelligenceRoute =
  RecruiterResumeIntelligenceRouteImport.update({
    id: '/resume-intelligence',
    path: '/resume-intelligence',
    getParentRoute: () => RecruiterRoute,
  } as any)
const RecruiterReportsRoute = RecruiterReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterRecommendationsRoute =
  RecruiterRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => RecruiterRoute,
  } as any)
const RecruiterPipelineRoute = RecruiterPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterPerformanceRoute = RecruiterPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterNotificationsRoute = RecruiterNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterMessagesRoute = RecruiterMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterJobsRoute = RecruiterJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterInterviewsRoute = RecruiterInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterInterviewInvitesRoute =
  RecruiterInterviewInvitesRouteImport.update({
    id: '/interview-invites',
    path: '/interview-invites',
    getParentRoute: () => RecruiterRoute,
  } as any)
const RecruiterInsightsRoute = RecruiterInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterDashboardRoute = RecruiterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterCompanyRoute = RecruiterCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterCandidatesRoute = RecruiterCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterApplicationsRoute = RecruiterApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterAnalyticsRoute = RecruiterAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterAiAnalysisRoute = RecruiterAiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => RecruiterRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const RecruiterJobsCreateRoute = RecruiterJobsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => RecruiterJobsRoute,
} as any)
const RecruiterInterviewMonitorInterviewIdRoute =
  RecruiterInterviewMonitorInterviewIdRouteImport.update({
    id: '/interview-monitor/$interviewId',
    path: '/interview-monitor/$interviewId',
    getParentRoute: () => RecruiterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/applications': typeof ApplicationsRoute
  '/coding': typeof CodingRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/video-resume': typeof VideoResumeRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/recruiter/ai-analysis': typeof RecruiterAiAnalysisRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/applications': typeof RecruiterApplicationsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/company': typeof RecruiterCompanyRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/insights': typeof RecruiterInsightsRoute
  '/recruiter/interview-invites': typeof RecruiterInterviewInvitesRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/jobs': typeof RecruiterJobsRouteWithChildren
  '/recruiter/messages': typeof RecruiterMessagesRoute
  '/recruiter/notifications': typeof RecruiterNotificationsRoute
  '/recruiter/performance': typeof RecruiterPerformanceRoute
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/recommendations': typeof RecruiterRecommendationsRoute
  '/recruiter/reports': typeof RecruiterReportsRoute
  '/recruiter/resume-intelligence': typeof RecruiterResumeIntelligenceRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/recruiter/shortlisted': typeof RecruiterShortlistedRoute
  '/recruiter/team': typeof RecruiterTeamRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/recruiter/interview-monitor/$interviewId': typeof RecruiterInterviewMonitorInterviewIdRoute
  '/recruiter/jobs/create': typeof RecruiterJobsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/applications': typeof ApplicationsRoute
  '/coding': typeof CodingRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/video-resume': typeof VideoResumeRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/recruiter/ai-analysis': typeof RecruiterAiAnalysisRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/applications': typeof RecruiterApplicationsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/company': typeof RecruiterCompanyRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/insights': typeof RecruiterInsightsRoute
  '/recruiter/interview-invites': typeof RecruiterInterviewInvitesRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/jobs': typeof RecruiterJobsRouteWithChildren
  '/recruiter/messages': typeof RecruiterMessagesRoute
  '/recruiter/notifications': typeof RecruiterNotificationsRoute
  '/recruiter/performance': typeof RecruiterPerformanceRoute
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/recommendations': typeof RecruiterRecommendationsRoute
  '/recruiter/reports': typeof RecruiterReportsRoute
  '/recruiter/resume-intelligence': typeof RecruiterResumeIntelligenceRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/recruiter/shortlisted': typeof RecruiterShortlistedRoute
  '/recruiter/team': typeof RecruiterTeamRoute
  '/recruiter': typeof RecruiterIndexRoute
  '/recruiter/interview-monitor/$interviewId': typeof RecruiterInterviewMonitorInterviewIdRoute
  '/recruiter/jobs/create': typeof RecruiterJobsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/applications': typeof ApplicationsRoute
  '/coding': typeof CodingRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/video-resume': typeof VideoResumeRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/recruiter/ai-analysis': typeof RecruiterAiAnalysisRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/applications': typeof RecruiterApplicationsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/company': typeof RecruiterCompanyRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/insights': typeof RecruiterInsightsRoute
  '/recruiter/interview-invites': typeof RecruiterInterviewInvitesRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/jobs': typeof RecruiterJobsRouteWithChildren
  '/recruiter/messages': typeof RecruiterMessagesRoute
  '/recruiter/notifications': typeof RecruiterNotificationsRoute
  '/recruiter/performance': typeof RecruiterPerformanceRoute
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/recommendations': typeof RecruiterRecommendationsRoute
  '/recruiter/reports': typeof RecruiterReportsRoute
  '/recruiter/resume-intelligence': typeof RecruiterResumeIntelligenceRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/recruiter/shortlisted': typeof RecruiterShortlistedRoute
  '/recruiter/team': typeof RecruiterTeamRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/recruiter/interview-monitor/$interviewId': typeof RecruiterInterviewMonitorInterviewIdRoute
  '/recruiter/jobs/create': typeof RecruiterJobsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/applications'
    | '/coding'
    | '/dashboard'
    | '/feedback'
    | '/help'
    | '/interview'
    | '/jobs'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/recruiter'
    | '/resume'
    | '/settings'
    | '/signup'
    | '/video-resume'
    | '/jobs/$jobId'
    | '/recruiter/ai-analysis'
    | '/recruiter/analytics'
    | '/recruiter/applications'
    | '/recruiter/candidates'
    | '/recruiter/company'
    | '/recruiter/dashboard'
    | '/recruiter/insights'
    | '/recruiter/interview-invites'
    | '/recruiter/interviews'
    | '/recruiter/jobs'
    | '/recruiter/messages'
    | '/recruiter/notifications'
    | '/recruiter/performance'
    | '/recruiter/pipeline'
    | '/recruiter/recommendations'
    | '/recruiter/reports'
    | '/recruiter/resume-intelligence'
    | '/recruiter/settings'
    | '/recruiter/shortlisted'
    | '/recruiter/team'
    | '/recruiter/'
    | '/recruiter/interview-monitor/$interviewId'
    | '/recruiter/jobs/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/applications'
    | '/coding'
    | '/dashboard'
    | '/feedback'
    | '/help'
    | '/interview'
    | '/jobs'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/resume'
    | '/settings'
    | '/signup'
    | '/video-resume'
    | '/jobs/$jobId'
    | '/recruiter/ai-analysis'
    | '/recruiter/analytics'
    | '/recruiter/applications'
    | '/recruiter/candidates'
    | '/recruiter/company'
    | '/recruiter/dashboard'
    | '/recruiter/insights'
    | '/recruiter/interview-invites'
    | '/recruiter/interviews'
    | '/recruiter/jobs'
    | '/recruiter/messages'
    | '/recruiter/notifications'
    | '/recruiter/performance'
    | '/recruiter/pipeline'
    | '/recruiter/recommendations'
    | '/recruiter/reports'
    | '/recruiter/resume-intelligence'
    | '/recruiter/settings'
    | '/recruiter/shortlisted'
    | '/recruiter/team'
    | '/recruiter'
    | '/recruiter/interview-monitor/$interviewId'
    | '/recruiter/jobs/create'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/applications'
    | '/coding'
    | '/dashboard'
    | '/feedback'
    | '/help'
    | '/interview'
    | '/jobs'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/recruiter'
    | '/resume'
    | '/settings'
    | '/signup'
    | '/video-resume'
    | '/jobs/$jobId'
    | '/recruiter/ai-analysis'
    | '/recruiter/analytics'
    | '/recruiter/applications'
    | '/recruiter/candidates'
    | '/recruiter/company'
    | '/recruiter/dashboard'
    | '/recruiter/insights'
    | '/recruiter/interview-invites'
    | '/recruiter/interviews'
    | '/recruiter/jobs'
    | '/recruiter/messages'
    | '/recruiter/notifications'
    | '/recruiter/performance'
    | '/recruiter/pipeline'
    | '/recruiter/recommendations'
    | '/recruiter/reports'
    | '/recruiter/resume-intelligence'
    | '/recruiter/settings'
    | '/recruiter/shortlisted'
    | '/recruiter/team'
    | '/recruiter/'
    | '/recruiter/interview-monitor/$interviewId'
    | '/recruiter/jobs/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CodingRoute: typeof CodingRoute
  DashboardRoute: typeof DashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  HelpRoute: typeof HelpRoute
  InterviewRoute: typeof InterviewRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RecruiterRoute: typeof RecruiterRouteWithChildren
  ResumeRoute: typeof ResumeRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VideoResumeRoute: typeof VideoResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-resume': {
      id: '/video-resume'
      path: '/video-resume'
      fullPath: '/video-resume'
      preLoaderRoute: typeof VideoResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding': {
      id: '/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof CodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/': {
      id: '/recruiter/'
      path: '/'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof RecruiterIndexRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/team': {
      id: '/recruiter/team'
      path: '/team'
      fullPath: '/recruiter/team'
      preLoaderRoute: typeof RecruiterTeamRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/shortlisted': {
      id: '/recruiter/shortlisted'
      path: '/shortlisted'
      fullPath: '/recruiter/shortlisted'
      preLoaderRoute: typeof RecruiterShortlistedRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/settings': {
      id: '/recruiter/settings'
      path: '/settings'
      fullPath: '/recruiter/settings'
      preLoaderRoute: typeof RecruiterSettingsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/resume-intelligence': {
      id: '/recruiter/resume-intelligence'
      path: '/resume-intelligence'
      fullPath: '/recruiter/resume-intelligence'
      preLoaderRoute: typeof RecruiterResumeIntelligenceRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/reports': {
      id: '/recruiter/reports'
      path: '/reports'
      fullPath: '/recruiter/reports'
      preLoaderRoute: typeof RecruiterReportsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/recommendations': {
      id: '/recruiter/recommendations'
      path: '/recommendations'
      fullPath: '/recruiter/recommendations'
      preLoaderRoute: typeof RecruiterRecommendationsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/pipeline': {
      id: '/recruiter/pipeline'
      path: '/pipeline'
      fullPath: '/recruiter/pipeline'
      preLoaderRoute: typeof RecruiterPipelineRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/performance': {
      id: '/recruiter/performance'
      path: '/performance'
      fullPath: '/recruiter/performance'
      preLoaderRoute: typeof RecruiterPerformanceRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/notifications': {
      id: '/recruiter/notifications'
      path: '/notifications'
      fullPath: '/recruiter/notifications'
      preLoaderRoute: typeof RecruiterNotificationsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/messages': {
      id: '/recruiter/messages'
      path: '/messages'
      fullPath: '/recruiter/messages'
      preLoaderRoute: typeof RecruiterMessagesRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/jobs': {
      id: '/recruiter/jobs'
      path: '/jobs'
      fullPath: '/recruiter/jobs'
      preLoaderRoute: typeof RecruiterJobsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/interviews': {
      id: '/recruiter/interviews'
      path: '/interviews'
      fullPath: '/recruiter/interviews'
      preLoaderRoute: typeof RecruiterInterviewsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/interview-invites': {
      id: '/recruiter/interview-invites'
      path: '/interview-invites'
      fullPath: '/recruiter/interview-invites'
      preLoaderRoute: typeof RecruiterInterviewInvitesRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/insights': {
      id: '/recruiter/insights'
      path: '/insights'
      fullPath: '/recruiter/insights'
      preLoaderRoute: typeof RecruiterInsightsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/dashboard': {
      id: '/recruiter/dashboard'
      path: '/dashboard'
      fullPath: '/recruiter/dashboard'
      preLoaderRoute: typeof RecruiterDashboardRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/company': {
      id: '/recruiter/company'
      path: '/company'
      fullPath: '/recruiter/company'
      preLoaderRoute: typeof RecruiterCompanyRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/candidates': {
      id: '/recruiter/candidates'
      path: '/candidates'
      fullPath: '/recruiter/candidates'
      preLoaderRoute: typeof RecruiterCandidatesRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/applications': {
      id: '/recruiter/applications'
      path: '/applications'
      fullPath: '/recruiter/applications'
      preLoaderRoute: typeof RecruiterApplicationsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/analytics': {
      id: '/recruiter/analytics'
      path: '/analytics'
      fullPath: '/recruiter/analytics'
      preLoaderRoute: typeof RecruiterAnalyticsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/ai-analysis': {
      id: '/recruiter/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/recruiter/ai-analysis'
      preLoaderRoute: typeof RecruiterAiAnalysisRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/recruiter/jobs/create': {
      id: '/recruiter/jobs/create'
      path: '/create'
      fullPath: '/recruiter/jobs/create'
      preLoaderRoute: typeof RecruiterJobsCreateRouteImport
      parentRoute: typeof RecruiterJobsRoute
    }
    '/recruiter/interview-monitor/$interviewId': {
      id: '/recruiter/interview-monitor/$interviewId'
      path: '/interview-monitor/$interviewId'
      fullPath: '/recruiter/interview-monitor/$interviewId'
      preLoaderRoute: typeof RecruiterInterviewMonitorInterviewIdRouteImport
      parentRoute: typeof RecruiterRoute
    }
  }
}

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface RecruiterJobsRouteChildren {
  RecruiterJobsCreateRoute: typeof RecruiterJobsCreateRoute
}

const RecruiterJobsRouteChildren: RecruiterJobsRouteChildren = {
  RecruiterJobsCreateRoute: RecruiterJobsCreateRoute,
}

const RecruiterJobsRouteWithChildren = RecruiterJobsRoute._addFileChildren(
  RecruiterJobsRouteChildren,
)

interface RecruiterRouteChildren {
  RecruiterAiAnalysisRoute: typeof RecruiterAiAnalysisRoute
  RecruiterAnalyticsRoute: typeof RecruiterAnalyticsRoute
  RecruiterApplicationsRoute: typeof RecruiterApplicationsRoute
  RecruiterCandidatesRoute: typeof RecruiterCandidatesRoute
  RecruiterCompanyRoute: typeof RecruiterCompanyRoute
  RecruiterDashboardRoute: typeof RecruiterDashboardRoute
  RecruiterInsightsRoute: typeof RecruiterInsightsRoute
  RecruiterInterviewInvitesRoute: typeof RecruiterInterviewInvitesRoute
  RecruiterInterviewsRoute: typeof RecruiterInterviewsRoute
  RecruiterJobsRoute: typeof RecruiterJobsRouteWithChildren
  RecruiterMessagesRoute: typeof RecruiterMessagesRoute
  RecruiterNotificationsRoute: typeof RecruiterNotificationsRoute
  RecruiterPerformanceRoute: typeof RecruiterPerformanceRoute
  RecruiterPipelineRoute: typeof RecruiterPipelineRoute
  RecruiterRecommendationsRoute: typeof RecruiterRecommendationsRoute
  RecruiterReportsRoute: typeof RecruiterReportsRoute
  RecruiterResumeIntelligenceRoute: typeof RecruiterResumeIntelligenceRoute
  RecruiterSettingsRoute: typeof RecruiterSettingsRoute
  RecruiterShortlistedRoute: typeof RecruiterShortlistedRoute
  RecruiterTeamRoute: typeof RecruiterTeamRoute
  RecruiterIndexRoute: typeof RecruiterIndexRoute
  RecruiterInterviewMonitorInterviewIdRoute: typeof RecruiterInterviewMonitorInterviewIdRoute
}

const RecruiterRouteChildren: RecruiterRouteChildren = {
  RecruiterAiAnalysisRoute: RecruiterAiAnalysisRoute,
  RecruiterAnalyticsRoute: RecruiterAnalyticsRoute,
  RecruiterApplicationsRoute: RecruiterApplicationsRoute,
  RecruiterCandidatesRoute: RecruiterCandidatesRoute,
  RecruiterCompanyRoute: RecruiterCompanyRoute,
  RecruiterDashboardRoute: RecruiterDashboardRoute,
  RecruiterInsightsRoute: RecruiterInsightsRoute,
  RecruiterInterviewInvitesRoute: RecruiterInterviewInvitesRoute,
  RecruiterInterviewsRoute: RecruiterInterviewsRoute,
  RecruiterJobsRoute: RecruiterJobsRouteWithChildren,
  RecruiterMessagesRoute: RecruiterMessagesRoute,
  RecruiterNotificationsRoute: RecruiterNotificationsRoute,
  RecruiterPerformanceRoute: RecruiterPerformanceRoute,
  RecruiterPipelineRoute: RecruiterPipelineRoute,
  RecruiterRecommendationsRoute: RecruiterRecommendationsRoute,
  RecruiterReportsRoute: RecruiterReportsRoute,
  RecruiterResumeIntelligenceRoute: RecruiterResumeIntelligenceRoute,
  RecruiterSettingsRoute: RecruiterSettingsRoute,
  RecruiterShortlistedRoute: RecruiterShortlistedRoute,
  RecruiterTeamRoute: RecruiterTeamRoute,
  RecruiterIndexRoute: RecruiterIndexRoute,
  RecruiterInterviewMonitorInterviewIdRoute:
    RecruiterInterviewMonitorInterviewIdRoute,
}

const RecruiterRouteWithChildren = RecruiterRoute._addFileChildren(
  RecruiterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApplicationsRoute: ApplicationsRoute,
  CodingRoute: CodingRoute,
  DashboardRoute: DashboardRoute,
  FeedbackRoute: FeedbackRoute,
  HelpRoute: HelpRoute,
  InterviewRoute: InterviewRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RecruiterRoute: RecruiterRouteWithChildren,
  ResumeRoute: ResumeRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VideoResumeRoute: VideoResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
